$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: default
endpoint_name: azure-ai-ml-ops-batch
model: azureml:azure-ai-ml-ops-model:1
code_configuration:
  code: code
  scoring_script: batch_driver.py
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
  conda_file: conda.yml
compute: azureml:cpu-batch
resources:
  instance_count: 1
max_concurrency_per_instance: 2
mini_batch_size: 10
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 3
  timeout: 60
error_threshold: -1
logging_level: info
