$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: azure-ai-ml-ops-training
display_name: azure-ai-ml-ops-training
inputs:
  input:
    type: uri_file
    path: azureml:azure-ai-ml-ops-training-data:1
  champion_metric:
    type: number
    default: -1.0
outputs:
  train_data:
  test_data:
  trained_model:
  evaluation_output:
  model_info_output:
settings:

  default_compute: azureml:cpu-training

  default_datastore: azureml:workspaceblobstore
  continue_on_step_failure: false
jobs:
  prepare:
    type: command
    code: ../../../data-science/src
    environment: azureml:azure-ai-ml-ops-train-env:1

    command: >-
      python prepare.py --input ${{inputs.input}}
      --train-output ${{outputs.train}}
      --test-output ${{outputs.test}}
    inputs:
      input: ${{parent.inputs.input}}
    outputs:
      train: ${{parent.outputs.train_data}}
      test: ${{parent.outputs.test_data}}
  train:
    type: command
    code: ../../../data-science/src
    environment: azureml:azure-ai-ml-ops-train-env:1

    command: python train.py --train-data ${{inputs.train}} --model-output ${{outputs.model}}
    inputs:
      train: ${{parent.jobs.prepare.outputs.train}}
    outputs:
      model: ${{parent.outputs.trained_model}}
  evaluate:
    type: command
    code: ../../../data-science/src
    environment: azureml:azure-ai-ml-ops-train-env:1

    command: >-
      python evaluate.py --model-name azure-ai-ml-ops-model
      --model-input ${{inputs.model}} --test-data ${{inputs.test}}
      --output ${{outputs.evaluation}} --champion-metric ${{inputs.champion_metric}}
      --minimum-improvement 0.01
    inputs:
      model: ${{parent.jobs.train.outputs.model}}
      test: ${{parent.jobs.prepare.outputs.test}}
      champion_metric: ${{parent.inputs.champion_metric}}
    outputs:
      evaluation: ${{parent.outputs.evaluation_output}}
  register:
    type: command
    code: ../../../data-science/src
    environment: azureml:azure-ai-ml-ops-train-env:1

    command: >-
      python register.py --model-name azure-ai-ml-ops-model
      --model-input ${{inputs.model}} --decision-input ${{inputs.decision}}
      --output ${{outputs.info}}
    inputs:
      model: ${{parent.jobs.train.outputs.model}}
      decision: ${{parent.jobs.evaluate.outputs.evaluation}}
    outputs:
      info: ${{parent.outputs.model_info_output}}
